#!/usr/bin/env python3
"""
analyze.py — Robust post-processing for the causal-AI-soviet example.

Scans:
- Newly harvested findings/papers.jsonl (from run_demo.sh)
- Pre-fetched key paper texts in ../../data/texts/
- Hard-coded "star" papers from our swarm exploration

Produces:
- Console summary
- findings/summary_report.md

This makes the example easy to re-create and extend without depending on
fragile jq parsing in every run.
"""

import json
import os
import glob
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent.parent
DATA_TEXTS = ROOT / "data" / "texts"
FINDINGS_DIR = HERE / "findings"
OUTPUT_REPORT = FINDINGS_DIR / "summary_report.md"

# Key papers identified in our exploration (with short AI mapping notes)
STAR_PAPERS = {
    "ru-197001.08938": {
        "title": "CAPACITIES OF INFORMATION SYSTEMS WITH FEEDBACKS AND INTERNAL INTERFERENCE",
        "why": "Spectral treatment of feedback loops + internal Gaussian interference. Directly relevant to info-theoretic causal bounds in systems with cycles/feedback.",
        "ai_map": "Feedback SCMs, directed information under interference, causal effect bounds in closed-loop systems.",
    },
    "ru-197001.75216": {
        "title": "ON AN ECONOMICAL CONSTRUCTION OF THE TRANSITIVE CLOSURE OF A DIRECTED GRAPH",
        "why": "Efficient algorithms for reachability/ancestry on directed graphs (DAG focus + decomposition).",
        "ai_map": "Fast ancestral sets, transitive reduction, descendant computation in large causal graphs.",
    },
    "ru-197001.37210": {
        "title": "ENTROPY OF A SHIFT AND MARKOV MEASURES IN THE PATH SPACE OF A COUNTABLE GRAPH",
        "why": "Markov measures and entropy on path spaces of directed graphs (topological Markov chains).",
        "ai_map": "Graph-structured world models, path-based causal processes, max-entropy representations for agents/sequences.",
    },
    "ru-197001.65870": {
        "title": "IDEALLY OBSERVABLE SYSTEMS",
        "why": "Ideal observability: reconstruct state independent of unknown controls/interventions. Algebraic rank conditions.",
        "ai_map": "Policy-agnostic identifiability, do-operator robustness, causal state estimation in RL/POMDPs.",
    },
    "ru-197001.25427": {
        "title": "ON THE APPLICATION OF THE METHOD OF FAST MATRIX MULTIPLICATION TO THE PROBLEM OF FINDING THE TRANSITIVE CLOSURE OF A GRAPH",
        "why": "Applies fast matrix methods (Strassen-era) to directed graph transitive closure.",
        "ai_map": "Scalable operations on causal graphs (ancestry, path enumeration) in discovery or query engines.",
    },
    "ru-197001.78384": {
        "title": "On the structure of differential games",
        "why": "Set-valued strategies, absorption sets, and stability in differential games with structure.",
        "ai_map": "Causal games, adversarial/multi-agent causality, robust reachability under interventions.",
    },
}

def load_jsonl(path):
    items = []
    if path.exists():
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        items.append(json.loads(line))
                    except:
                        pass
    return items

def extract_from_text_md(id_):
    """Pull title + first ~300 chars from pre-fetched text if available."""
    md_path = DATA_TEXTS / f"{id_}.md"
    if not md_path.exists():
        return None, None
    text = md_path.read_text(errors="ignore")
    lines = text.splitlines()
    title = ""
    abstract = ""
    for i, line in enumerate(lines):
        if line.startswith("# ") and not title:
            title = line[2:].strip()
        if "abstract" in line.lower() or (i > 5 and len(abstract) < 50):
            abstract = " ".join(lines[i:i+5])[:300]
            break
    if not abstract:
        abstract = text[:400].replace("\n", " ")
    return title or "Unknown", abstract

def main():
    os.makedirs(FINDINGS_DIR, exist_ok=True)

    # Load any newly harvested data
    harvested = load_jsonl(FINDINGS_DIR / "papers.jsonl")
    search_results = load_jsonl(FINDINGS_DIR / "search_results.jsonl")
    all_papers = {p["id"]: p for p in harvested + search_results if "id" in p}

    report_lines = []
    report_lines.append("# Causal AI Soviet Research — Example Findings\n")
    report_lines.append("Generated by the reproducible demo in `examples/causal-ai-soviet/`.\n")
    report_lines.append("This report highlights papers surfaced via `sovietrxiv.sh` searches + harvest that show strong potential mappings to modern causal AI (SCMs, graphical models, causal RL, identifiability, etc.).\n")
    report_lines.append("## Methodology\n")
    report_lines.append("- Used `./sovietrxiv.sh search \"term\"` for \"feedback\", \"markov\", \"graph\", \"observab\", \"structure\", etc. (default russiarxiv source).\n")
    report_lines.append("- Small focused harvest via the tool.\n")
    report_lines.append("- Analysis combines tool output with pre-fetched full texts in `../data/texts/`.\n")
    report_lines.append("- Emphasis on structural, graphical, feedback, and inference ideas from 1960s-1970 Soviet cybernetics/control theory.\n\n")

    report_lines.append("## Star Papers (High Potential for Causal AI)\n")

    for pid, meta in STAR_PAPERS.items():
        p = all_papers.get(pid, {})
        title = p.get("title") or meta["title"]
        abstract = p.get("abstract", "")
        if not abstract:
            _, abstract = extract_from_text_md(pid)
        report_lines.append(f"### {pid} — {title}\n")
        if abstract:
            report_lines.append(f"**Excerpt:** {abstract[:350]}...\n\n")
        report_lines.append(f"**Why interesting (from our analysis):** {meta['why']}\n\n")
        report_lines.append(f"**Modern causal AI mapping:** {meta['ai_map']}\n\n")
        report_lines.append(f"**Reproduce:** `./sovietrxiv.sh get {pid}` or `./sovietrxiv.sh text {pid} --save`\n\n")
        report_lines.append("---\n\n")

    # Add any other interesting harvested papers
    report_lines.append("## Other Papers from This Run\n")
    interesting = []
    keywords = ["feedback", "graph", "markov", "observ", "structure", "control law", "stability", "differential game", "information system"]
    for p in all_papers.values():
        text = (p.get("title","") + " " + p.get("abstract","")).lower()
        if any(k in text for k in keywords):
            interesting.append(p)
    for p in interesting[:8]:
        if p["id"] in STAR_PAPERS:
            continue
        report_lines.append(f"- **{p['id']}**: {p.get('title','')[:80]}\n")
        report_lines.append(f"  {p.get('abstract','')[:180]}...\n")
        report_lines.append(f"  Reproduce: `./sovietrxiv.sh get {p['id']}`\n\n")

    report_lines.append("## How to Extend This Example\n")
    report_lines.append("1. `rm -rf findings/` then re-run `run_demo.sh` (with `SOVIETRXIV_EMAIL` set for speed).\n")
    report_lines.append("2. Edit this script or add more targeted `search` calls in `run_demo.sh`.\n")
    report_lines.append("3. For full texts: `./sovietrxiv.sh text <id> --save` (saves to `data/texts/`). Then re-run analysis.\n")
    report_lines.append("4. See root `whitepaper.md` for the full hypothesis, swarm methodology, and deeper discussion.\n\n")

    report_lines.append("All credit to the original SovietRxiv project and authors for the data and translations.\n")

    with open(OUTPUT_REPORT, "w") as f:
        f.writelines(report_lines)

    print("Analysis complete. Report written to:", OUTPUT_REPORT)
    print("\n=== Quick Console Summary ===")
    print("Star papers analyzed:")
    for pid in list(STAR_PAPERS.keys())[:5]:
        print(f"  - {pid}")
    print(f"\nTotal candidate papers considered: {len(all_papers)}")
    print("Full report: findings/summary_report.md")

if __name__ == "__main__":
    main()
